import {Item} from "./item";

/**
 * @description
 * All items that are already shown and cant be removed, replaced or reordered.
 */
export const FIX_ITEMS: Item[] = [
    {text: 'Nach Rügen fahren und dort mit einem VW Caddy Maxi Campen', emoji: '🏕️', done: true},
    {text: 'Im Regen in Pfützen springen', emoji: '🧒', done: true},
    {text: 'Wandern im Deister', emoji: '🥾', done: true},
    {text: 'Urlaub auf einem Hausboot machen', emoji: '🚤', done: true},
    {text: 'Ein Kinderbild nachstellen', emoji: '🖼️'},
    {text: 'In Wilhelmshaven mit einem Segelschiff fahren', emoji: '⛵', done: true},
    {text: 'Einem Escape-Room entkommen', emoji: '🗝️', done: true},
    {text: 'Bei einem Craftbeer-Tasting mitmachen', emoji: '🍺'},
    {text: 'Einen Telefonstreich machen', emoji: '📞'},
    {text: 'Bei einer Halloween-Kostüm-Party den ersten Preis gewinnen!', emoji: '🎃', done: true},
    {text: 'Ein Lied im Radio wünschen', emoji: '📻'},
    {text: 'Anfangen ein Instrument zu lernen', emoji: '🎸'},
    {text: 'Ein neues Buch anfangen', emoji: '📖', done: true},
    {text: 'Bingo spielen und laut Bingo rufen', emoji: '🎲', dont: true},
    {text: 'Ein 5000-Teile Puzzle schaffen', emoji: '🧩', dont: true},
    {text: 'An einem Ort in deiner Stadt Müll aufräumen', emoji: '🛢️', done: true},
    {text: 'In einem syrischen Restaurant essen gehen', emoji: '🧆', done: true},
    {text: 'Etwas gemeinnütziges tun', emoji: '🍲'},
    {text: 'Insekten essen', emoji: '🐛', dont: true},
    {text: 'Einen Tanzkurs besuchen', emoji: '💃🕺'},
    {text: 'Ein Bild fürs eigene Zuhause malen', emoji: '🖼️', done: true},
    {text: 'Bei einem Dinner im Dunkeln mitmachen', emoji: '◼️'},
    {text: 'eine Schlittenfahrt im Schnee machen', emoji: '🛷'},
    {text: 'In einer heißen Quelle baden', emoji: '♨️'},
    {text: 'Die Polarlichter sehen', emoji: '🦄'},
    {text: 'Einen Töpferkurs besuchen', emoji: '🍯'},
    {text: 'Eine Kerze selbermachen', emoji: '🕯️'},
    {text: 'Einen Dankesbrief an eine Firma schreiben', emoji: '', dont: true},
    {text: 'In einen Indoor Trampolin-Park gehen', emoji: '🎫'},
    {text: 'Bei einer Pub-Quiznacht mitmachen', emoji: '🍺️', done: true},
    {text: 'Bouldern gehen', emoji: '🧗'},
    {text: 'Auf einem Kamel reiten', emoji: '🐫'},
    {text: 'Auf einer Vespa durch Italien fahren', emoji: '🛵'},
    {text: 'Zorbing', emoji: '🎱'},
    {text: 'Eine Zeitkapsel vergraben', emoji: '⏳'},
    {text: 'Ein Kartenhaus bauen', emoji: '🃏'},
    {text: 'Makremee machen', emoji: '🧵', done: true},
    {text: 'Papier selber machen', emoji: '📝', done: true},
    {text: 'Origami falten', emoji: '🐭'},
    {text: 'Blumen pressen', emoji: '🍀'},
    {text: 'Milo begrüßen', emoji: '🐶❤️', done: true},
    {text: 'Ein Mandala malen', emoji: '🖍️'},
    {text: 'Einen Brief an ein:e Freund:in schreiben', emoji: '💌'},
    {text: 'Eine Zigarre rauchen', emoji: '🚬', done: true},
    {text: 'Shuffleboard spielen', emoji: '🥌️', done: true},
    {text: 'Einen Handabdruck in feuchtem Zement hinterlassen', emoji: '🖐'},
    {text: 'Jemanden mit dem gleichen Namen kontaktieren', emoji: '👭'},
    {text: 'Gin selber machen', emoji: '🍸'},
    {text: 'Unseren neuen Van anmelden', emoji: '🚐❤️', done: true},
    {text: 'Zu einem Schiffswrack tauchen', emoji: '🚢'},
    {
        text: '<a href="https://www.indoor-skydiving.com/UI/Booking/bookPackage.aspx?lang=1&type=30">Indoor Skydiven</a>',
        emoji: '🪂'
    },
    {text: 'Einen Vulkan besteigen', emoji: '🌋'},
    {text: 'Unseren Jahrestag feiern!', emoji: '❤️', done: true},
    {text: 'Eine Englischsprachschule besuchen', emoji: '🇬🇧'},
    {text: 'Bei einer Überraschungsparty mitmachen', emoji: '🎉', done: true},
    {text: 'Zu einem Feld fahren und einen Blumenstrauß binden', emoji: '💐'},
    {text: 'Unser erste Date wiederholen', emoji: '🍦', done: true},
    {text: 'Schlittschuhlaufen', emoji: '⛸️'},
    {text: 'Neue Restaurants ausprobieren', emoji: '🍢'},
];
